### ISSUE TITLE
Image API

### ISSUE THREAD

**Issue by emilybaum** [emilybaum/thissociety#3]
## User Story
As young adult, I want to be able to see photos (from Pixabay) that relate to my interest, so that I am inspired to pursue my passion

## Acceptance Criteria - #2 
- [x] Have a working API with Pixabay to get images related to the user interest
- [x] Select 4 random images from JSON object
- [x] Store image details in a new object for use across future pages
- [x] Display photo details on the page

**Comment by emilybaum** [comment]
Can you guys see this comment?

**Comment by TheAce75** [comment]
YESSSSSS

**Comment by ghost** [comment]
yes
